build: fliglio mysql rabbitmq chinchilla

fliglio:
	docker build -t benschw/horde-fliglio ./fliglio/

mysql:
	docker build -t benschw/horde-mysql ./mysql/

rabbitmq:
	docker build -t benschw/horde-rabbitmq ./rabbitmq/

chinchilla:
	docker build -t benschw/horde-chinchilla ./chinchilla/

.PHONY: fliglio mysql rabbitmq chinchilla
